import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "../components/Footer";
import ResponseContextProvider from "@/contexts/ResponseContextProvider";
import ThemeContextProvider from "@/contexts/ThemeContextProvider";
import ThemeSwitch from "@/components/ThemeSwitch";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-800 relative pt-28 sm:pt-36 
      dark:bg-gray-800 dark:text-gray-100 dark:text-opacity-90`}>
    <div className="bg-[#e0f7ff] absolute top-[-6rem] -z-10 right-[0rem] h-[50rem] w-[50rem] 
      rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#4a687d]">
    </div>
    <div className="bg-[#d3d8e3] absolute top-[-1rem] -z-10 left-[-35rem] h-[36rem] w-[50rem] rounded-full 
      blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#3e4452]">
    </div>
      <ThemeContextProvider>
        <ResponseContextProvider>
          {children}
          <Footer />
        </ResponseContextProvider>
        <ThemeSwitch />
      </ThemeContextProvider>
      </body>
    </html>
  );
}
